### ISSUE TITLE
Not working with privacy.firstparty.isolate

### ISSUE THREAD

**Issue by grenzor** [dsrini-open/kill-cookies#1]
Thanks for the addon but it looks like if privacy.firstparty.isolate is set to true it is unable to delete cookies. Can support for privacy.firstparty.isolate be added?

**Comment by dsrini-open** [comment]
Adding the request. Thanks!

**Comment by dsrini-open** [comment]
Please test with changes of v1.1
(Should be available soon through Mozilla channel, if no review changes)

**Comment by grenzor** [comment]
For some reason the addon can't seem to detect any cookies at all with default install. I can only see the `Kill All Cookies` and `Kill All but ignored` buttons. Is it the same on your side?

**Comment by dsrini-open** [comment]
The first screenshot is with isolate option, the next without. Just tried with Firefox Dev edition - 
Could you verify that you haven't turned off the options "List all cookies?" in options page?

![withisolateoption](https://user-images.githubusercontent.com/7321719/40002027-198738f4-5755-11e8-9eee-3b487742900d.png)
![withoutisolateoption](https://user-images.githubusercontent.com/7321719/40002028-19d34884-5755-11e8-879e-852544f1d105.png)

**Comment by grenzor** [comment]
All options including `List all cookies` are ticked (except `Only show top domains`). I'm using beta 61. Not really sure what could be causing this with, checked extensions and haven't changed anything in a while.

**Comment by dsrini-open** [comment]
Just tried in linux with a fresh new install. Works fine for me. Could you please try with a fresh new install or a different profile (any other version)? 
Or do you see any error message in browser console (Ctrl+Shift+J) (There might be many logs, just try clearing all logs, and then launch the addon popup and see if there are any new logs)

**Comment by grenzor** [comment]
Tried in a new install works for me too. Weird why my normal profiles doesn't show those options. Maybe I have some config value toggled which messes with it..
